// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoMdYOFlXyNujknWpAXl0aMxuK5C8Lnng',
    appId: '1:818340725320:web:45487080ee680d4f860e7d',
    messagingSenderId: '818340725320',
    projectId: 'nutricare16',
    authDomain: 'nutricare16.firebaseapp.com',
    storageBucket: 'nutricare16.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC2LCGuZuosvJ5jLyn2xyLeSNDhTeYNgs',
    appId: '1:818340725320:android:27a262b86763abbf860e7d',
    messagingSenderId: '818340725320',
    projectId: 'nutricare16',
    storageBucket: 'nutricare16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC96CsTuh9FH_aFczYQ6kmhehW3NyNMrHo',
    appId: '1:818340725320:ios:ad76f714cbe732c8860e7d',
    messagingSenderId: '818340725320',
    projectId: 'nutricare16',
    storageBucket: 'nutricare16.firebasestorage.app',
    iosBundleId: 'com.example.nutricare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC96CsTuh9FH_aFczYQ6kmhehW3NyNMrHo',
    appId: '1:818340725320:ios:ad76f714cbe732c8860e7d',
    messagingSenderId: '818340725320',
    projectId: 'nutricare16',
    storageBucket: 'nutricare16.firebasestorage.app',
    iosBundleId: 'com.example.nutricare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoMdYOFlXyNujknWpAXl0aMxuK5C8Lnng',
    appId: '1:818340725320:web:5a30a0b9a5853264860e7d',
    messagingSenderId: '818340725320',
    projectId: 'nutricare16',
    authDomain: 'nutricare16.firebaseapp.com',
    storageBucket: 'nutricare16.firebasestorage.app',
  );
}
